return {
	corcrowd = {
		acceleration = 0.2,
		blocking = false,
		maxdec = 0.0725,
		energycost = 8200,
		metalcost = 410,
		buildpic = "CORTITAN.DDS",
		buildtime = 14700,
		canfly = true,
		canmove = true,
		category = "ALL NOTLAND MOBILE WEAPON VTOL NOTSUB NOTSHIP NOTHOVER",
		collide = true,
		cruisealtitude = 90,
		explodeas = "mediumexplosiongeneric",
		footprintx = 3,
		footprintz = 3,
		icontype = "air",
		idleautoheal = 5,
		idletime = 1800,
		maxacc = 0.1325,
		maxaileron = 0.01347,
		maxbank = 0.8,
		health = 1960,
		maxelevator = 0.00972,
		maxpitch = 0.625,
		maxrudder = 0.00522,
		maxslope = 10,
		speed = 279.0,
		maxwaterdepth = 0,
		nochasecategory = "VTOL",
		objectname = "Units/CORTITAN.s3o",
		radardistance = 800,
		script = "Units/CORTITAN.cob",
		seismicsignature = 0,
		selfdestructas = "mediumExplosionGenericSelfd",
		sightdistance = 500,
		sonardistance = 800,
		speedtofront = 0.063,
		turnradius = 64,
		turnrate = 600,
		usesmoothmesh = true,
		wingangle = 0.06222,
		wingdrag = 0.18,
		customparams = {
			unitgroup = 'sub',
			model_author = "Mr Bob",
			normaltex = "unittextures/cor_normal.dds",
			subfolder = "coraircraft/t2",
			techlevel = 2,
		},
		sfxtypes = {
			crashexplosiongenerators = {
				[1] = "crashing-small",
				[2] = "crashing-small",
				[3] = "crashing-small2",
				[4] = "crashing-small3",
				[5] = "crashing-small3",
			},
			pieceexplosiongenerators = {
				[1] = "airdeathceg3",
				[2] = "airdeathceg4",
				[3] = "airdeathceg2",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "vtolcrmv",
			},
			select = {
				[1] = "vtolcrac",
			},
		},
		weapondefs = {
			corskyflaks = {
				accuracy = 30,
				areaofeffect = 150,
				avoidfeature = false,
				avoidfriendly = true,
				burst = 8,
				burstrate = 0.04,
				burnblow = true,
				collidefriendly = true,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				dance = 90,
				edgeeffectiveness = 0.5,
				explosiongenerator = "custom:flak",
				flightTime = 4,
				model = "cormissile.s3o",
				name = "Flak missiles",
				noselfdamage = true,
				range = 800,
				reloadtime = 10,
				smokePeriod = 4,
				smoketime = 16,
				smoketrail = true,
				smokesize = 1.8,
				smokecolor = 0.55,
				soundhit = "flakhit2",
				soundhitwet = "splshbig",
				soundstart = "rocklit1",
				sprayangle = 20000,
				texture1 = "null",
				texture2 = "smoketrail",
				tracks = true,
				tolerance = 2250,
				turnrate = 6000,
				turret = false,
				weaponacceleration = 600,
				weapontype = "MissileLauncher",
				weaponvelocity = 200,
				wobble = 90,
				damage = {
					vtol = 100,
					default = 1,
				},

			},
		},
		weapons = {
			[1] = {
				def = "corskyflaks",
				onlytargetcategory = "VTOL",
			},
		},
	},
}
