return {
	corcrowd = {
		maxacc = 0.15,
		airsightdistance = 850,
		activatewhenbuilt = true,
		blocking = true,
		bankingallowed = false,
		maxdec = 0.15,
		energycost = 11200,
		metalcost = 1010,
		buildpic = "CORCRWH.DDS",
		buildtime = 34200,
		canfly = true,
		canmove = true,
		category = "ALL WEAPON VTOL NOTSUB NOTHOVER",
		collide = true,
		collisionvolumeoffsets = "0 1 17",
		collisionvolumescales = "55 28 80",
		collisionvolumetype = "Box",
		cruisealtitude = 85,
		explodeas = "largeexplosiongeneric",
		footprintx = 3,
		footprintz = 3,
		hoverattack = true,
		idleautoheal = 15,
		idletime = 1200,
		health = 6700,
		maxslope = 10,
		speed = 84.9,
		maxwaterdepth = 0,
		nochasecategory = "VTOL",
		objectname = "Units/CORCROWD.s3o",
		script = "Units/CORCROWD.cob",
		seismicsignature = 0,
		selfdestructas = "largeExplosionGenericSelfd",
		sightdistance = 494,
		turninplaceanglelimit = 360,
		turnrate = 300,
		upright = true,
		customparams = {
			maxrange = "425",
			unitgroup = 'weapon',
			model_author = "Mr Bob, Hornet",
			normaltex = "unittextures/cor_normal.dds",
			subfolder = "coraircraft/t2",
			techlevel = 2,
		},
		sfxtypes = {
			explosiongenerators = {
				[1] = "custom:flamestreamxxl",
			},
			crashexplosiongenerators = {
				[1] = "crashing-large",
				[2] = "crashing-large",
				[3] = "crashing-large2",
				[4] = "crashing-large3",
				[5] = "crashing-large3",
			},
			pieceexplosiongenerators = {
				[1] = "airdeathceg3",
				[2] = "airdeathceg4",
				[3] = "airdeathceg2",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "vtolcrmv",
			},
			select = {
				[1] = "vtolcrac",
			},
		},
		weapondefs = {
			corskyflaks = {
				accuracy = 30,
				areaofeffect = 250,
				avoidfeature = false,
				avoidfriendly = true,
				burst = 20,
				burstrate = 0.04,
				burnblow = true,
				collidefriendly = false,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				dance = 40,
				edgeeffectiveness = 0.8,
				explosiongenerator = "custom:genericshellexplosion-tiny-aa",
				model = "cormissile.s3o",
				name = "Flak missiles",
				noselfdamage = true,
				range = 900,
				reloadtime = 6,
				smokePeriod = 4,
				smoketime = 16,
				smoketrail = true,
				smokesize = 1.8,
				smokecolor = 0.55,
				soundhit = "flakhit2",
				soundhitwet = "splshbig",
				soundstart = "rocklit1",
				texture1 = "null",
				texture2 = "smoketrail",
				tracks = true,
				tolerance = 2250,

				turret = true,--being false might be optimal to allow flanking, but seems -really- fussy about targetting things properly
				weapontype = "MissileLauncher",



				customparams = {
					speceffect = "retarget",
					when = "always",
				},
				sprayangle = 20000,
				weaponacceleration = 100,
				flightTime = 3,
				weaponvelocity = 750,
				startvelocity = 200,
				wobble = 90,
				turnrate = 12000,
				damage = {
					vtol = 100,
					default = 1,
				},

			},
		},
		weapons = {
			[1] = {
				def = "corskyflaks",
				maindir = "0 0 1",
				maxangledif = 240,
				onlytargetcategory = "VTOL",
				fastautoretargeting = true,
			},
		},
	},
}
