return {
	corvrad = {
		maxacc = 0.02086,
		activatewhenbuilt = true,
		maxdec = 0.04172,
		energycost = 1300,
		metalcost = 92,
		buildpic = "CORVRAD.DDS",
		buildtime = 4220,
		canattack = true,
		canmove = true,
		category = "ALL TANK MOBILE NOTSUB NOWEAPON NOTSHIP NOTAIR NOTHOVER SURFACE EMPABLE",
		collisionvolumeoffsets = "0 0 0",
		collisionvolumescales = "24 18 29",
		collisionvolumetype = "box",
		corpse = "dead",
		explodeas = "smallexplosiongeneric",
		footprintx = 3,
		footprintz = 3,
		idleautoheal = 5,
		idletime = 1800,
		leavetracks = true,
		health = 570,
		maxslope = 16,
		speed = 48.0,
		maxwaterdepth = 0,
		movementclass = "TANK3",
		nochasecategory = "ALL",
		objectname = "Units/CORVRAD.s3o",
		onoffable = false,
		radardistance = 2200,
		script = "Units/CORVRAD.cob",
		seismicsignature = 0,
		selfdestructas = "smallExplosionGenericSelfd",
		sightdistance = 900,
		sonardistance = 0,
		trackstrength = 10,
		tracktype = "corwidetracks",
		trackwidth = 23,
		turninplace = true,
		turninplaceanglelimit = 90,
		turninplacespeedlimit = 0.825,
		turnrate = 315,
		customparams = {
			maxrange = 600,
			unitgroup = 'util',
			model_author = "Beherith",
			normaltex = "unittextures/cor_normal.dds",
			subfolder = "corvehicles/t2",
			techlevel = 2,
		},
		featuredefs = {
			dead = {
				blocking = true,
				category = "corpses",
				collisionvolumeoffsets = "-0.611381530762 -0.0270607836914 -0.43489074707",
				collisionvolumescales = "23.1105194092 8.20951843262 32.5806274414",
				collisionvolumetype = "Box",
				damage = 546,
				featuredead = "HEAP",
				footprintx = 2,
				footprintz = 2,
				height = 20,
				metal = 64,
				object = "Units/corvrad_dead.s3o",
				reclaimable = true,
			},
			heap = {
				blocking = false,
				category = "heaps",
				collisionvolumescales = "35.0 4.0 6.0",
				collisionvolumetype = "cylY",
				damage = 450,
				footprintx = 2,
				footprintz = 2,
				height = 4,
				metal = 48,
				object = "Units/cor2X2F.s3o",
				reclaimable = true,
				resurrectable = 0,
			},
		},
		sfxtypes = {
			explosiongenerators = {
				[1] = "custom:radarpulse_t2",
			},
			pieceexplosiongenerators = {
				[1] = "deathceg2",
				[2] = "deathceg3",
				[3] = "deathceg4",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "vcormove",
			},
			select = {
				[1] = "cvradsel",
			},
		},
		weapondefs = {
			corvoyr_rangefinder = {
				areaofeffect = 0,
				edgeeffectiveness = 0.65,
				firestarter = 0,
				name = "Rangefinder",
				noselfdamage = true,
				range = 600,
				reloadtime = 1,
				smoketrail = false,
				smokeTrailCastShadow = false,
				castshadow = false, --projectile
				texture1 = "null",
				texture2 = "smoketrailbar",
				texture3 = "null",
				tolerance = 4000,
				turnrate = 15000,
				weaponacceleration = 100,
				weapontimer = 3,
				weapontype = "Cannon",
				weaponvelocity = 415,
				damage = {
					default = 1,
				},
			},
		},
		weapons = {
			[1] = {
				badtargetcategory = "MOBILE",
				def = "corvoyr_rangefinder",
				onlytargetcategory = "SURFACE",
			},
		},
		weapondefs = {
			radjam_rangefinder = {
areaofeffect = 8,
				avoidfeature = false,
				beamtime = 0.1,
				beamttl = 1,
				corethickness = 0.165,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0.15,
				energypershot = 0,
				explosiongenerator = "custom:laserhit-small-red",
				firestarter = 50,
				impactonly = 1,
				impulseboost = 0,
				impulsefactor = 0,
				laserflaresize = 4.4,
				name = "Laser",
				noselfdamage = true,
				range = 230,
				reloadtime = 0.76667,
				rgbcolor = "1 0 0",
				soundhitdry = "",
				soundhitwet = "sizzle",
				soundstart = "lasrlit3",
				soundtrigger = 1,
				targetmoveerror = 0.12,
				thickness = 2.2,
				tolerance = 10000,
				turret = true,
				weapontype = "BeamLaser",
				weaponvelocity = 1000,
				damage = {
					default = 1,
				},
			},
		},
		weapons = {
			[1] = {
				badtargetcategory = "MOBILE",
				def = "radjam_rangefinder",
				onlytargetcategory = "SURFACE",
			},
		},
		
	},
}
